### ISSUE TITLE
We need Unity3d SDK

### ISSUE THREAD

**Issue by masterchop** [EnvelopVR/evr-sdk#1]
3d development in pure code is a very demanding situation.
Game Engines makes this really easy

**Comment by hoesing** [comment]
If you go to:

https://github.com/EnvelopVR/EnvelopVR.Evr/releases/tag/1.0.0

we already have pre-built .Net assemblies for Unity.  We don't have any sample code using this yet, but it should work for you, and is quite similar to the JavaScript API.

**Comment by masterchop** [comment]
Thank you, ill try to test this out.
